<?php
/**
 * @var \Codilar\Employee\Block\View $block
 */

$data = $block->getAllData();


?>
<div class="brand-listing">
    <h1>Our Employees</h1>
    <table>
        <thead>
        <tr>
            <th><?php echo __('Name') ?></th>
            <th>Is Enabled</th>
            <th>Description</th>
            <th>Email</th>
            <th>Address</th>
            <th>Phone Number</th>
        </tr>
        <tr>
            <td><?php echo $data->getName() ?></td>
            <td><?php echo $data->getIsActive() ? 'Yes': 'No' ?></td>
            <td><?php echo $data->getDescription() ?></td>
            <td><?php echo $data->getEmail() ?></td>
            <td><?php echo $data->getAddress() ?></td>
            <td><?php echo $data->getPhonenumber() ?></td>
        </tr>
        </thead>
    </table>
</div>
