<?php
/**
 * @var \Codilar\Employee\Block\View $block
 */

$employees = $block->getAllEmployees();

?>
<div class="brand-listing">
    <h1>Our Employees</h1>
    <table>
        <thead>
        <tr>
            <th><?php echo __('Name') ?></th>
            <th>Is Enabled</th>
            <th>Description</th>
            <th>Email</th>
            <th>Address</th>
            <th>Phone Number</th>
        </tr>
        <?php foreach ($block->getAllEmployees() as $employee): ?>
        <tr>
            <td><?php echo $employee->getName() ?></td>
            <td><?php echo $employee->getIsActive() ? 'Yes': 'No' ?></td>
            <td><?php echo $employee->getDescription() ?></td>
            <td><?php echo $employee->getEmail() ?></td>
            <td><?php echo $employee->getAddress() ?></td>
            <td><?php echo $employee->getPhonenumber() ?></td>
        </tr>
        <?php endforeach; ?>
        </thead>
    </table>
</div>
