<?php
/**
 * @var \Codilar\Employee\Block\View $block
 */

?>
<form style="padding: 1rem; margin-top: 1rem; border: 1px solid silver" method="POST" action="<?php echo $block->getView() ?>" >
        <h3>Add new Employee Detail</h3>
        <div>
            <label>Is Enabled</label>
            <select name="is_active">
                <option value="0">No</option>
                <option value="1">Yes</option>
           </select>
        </div>
        <div>
            <label>Name</label>
            <input name="name" type="text" />
        </div>
    <div>
        <label>Email</label>
        <input name="email" type="text" />
    </div>
    <div>
        <label>Phone Number</label>
        <input name="phonenumber" type="number" />
    </div>
        <div>
            <div>
                <label>Address</label>
                <input name="address" type="text" />
            </div>
            <label>Descripton</label>
            <textarea name="description"></textarea>
        </div>
        <button>Add</button>
    </form>
